### ISSUE TITLE
Sponge

### ISSUE THREAD

**Issue by PixelmonPRO** [Team-Fruit/SignPictureManager#1]
Hello! Could you port this plugin for sponge?
Mod is very good, but without permissions there will be chaos on the server(

**Comment by sjcl** [comment]
Sorry for the late reply. 
This plugin is developed with Sponge 1.8.9. It is easy to manage SignPicture placed on the server.

**Comment by sjcl** [comment]
Sorry for late reply. 
This plugin works in conjunction with Mod. After that is done, I am thinking about porting to Sponge.

**Comment by PixelmonPRO** [comment]
Any news?)

**Comment by PixelmonPRO** [comment]
@sjcl

**Comment by sjcl** [comment]
I'm sorry! We will work on the specification of the API.
